"use client";
import Sidebar from "./components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import {useRouter, usePathname, useSearchParams } from 'next/navigation'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const pathname = usePathname();

  console.log('ss',pathname)

  const basisWidth=pathname !== '/login' ? '4/5' : 'full'
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen overflow-hidden flex flex-row ">
        {  pathname !== '/login' &&
          <div className="basis-1/5 h-full ">
          <Sidebar />
          </div>
        }
          <div className={`basis-${basisWidth} h-full bg-[#F8F7F7]`}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
