
import Sidebar from "../components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen overflow-hidden flex flex-row">
          <div className="basis-1/5 h-full ">
            <Sidebar />
          </div>
          <div className="basis-4/5 h-full bg-[#F8F7F7]">
            {children}
            
          </div>
        </div>
      </body>
    </html>
  );
}
